/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FrankyAiRouteImport } from './routes/franky-ai'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as UnitIdRouteImport } from './routes/unit.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FrankyAiRoute = FrankyAiRouteImport.update({
  id: '/franky-ai',
  path: '/franky-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitIdRoute = UnitIdRouteImport.update({
  id: '/unit/$id',
  path: '/unit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/franky-ai': typeof FrankyAiRoute
  '/library': typeof LibraryRoute
  '/api/chat': typeof ApiChatRoute
  '/unit/$id': typeof UnitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/franky-ai': typeof FrankyAiRoute
  '/library': typeof LibraryRoute
  '/api/chat': typeof ApiChatRoute
  '/unit/$id': typeof UnitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/franky-ai': typeof FrankyAiRoute
  '/library': typeof LibraryRoute
  '/api/chat': typeof ApiChatRoute
  '/unit/$id': typeof UnitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/franky-ai'
    | '/library'
    | '/api/chat'
    | '/unit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/franky-ai'
    | '/library'
    | '/api/chat'
    | '/unit/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/franky-ai'
    | '/library'
    | '/api/chat'
    | '/unit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  FrankyAiRoute: typeof FrankyAiRoute
  LibraryRoute: typeof LibraryRoute
  ApiChatRoute: typeof ApiChatRoute
  UnitIdRoute: typeof UnitIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/franky-ai': {
      id: '/franky-ai'
      path: '/franky-ai'
      fullPath: '/franky-ai'
      preLoaderRoute: typeof FrankyAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unit/$id': {
      id: '/unit/$id'
      path: '/unit/$id'
      fullPath: '/unit/$id'
      preLoaderRoute: typeof UnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  FrankyAiRoute: FrankyAiRoute,
  LibraryRoute: LibraryRoute,
  ApiChatRoute: ApiChatRoute,
  UnitIdRoute: UnitIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
