ALTER TABLE public.materials ADD COLUMN IF NOT EXISTS content text, ADD COLUMN IF NOT EXISTS unit_code text, ADD COLUMN IF NOT EXISTS level text;
DELETE FROM public.materials WHERE external_url IS NOT NULL AND file_path IS NULL;
INSERT INTO public.materials (title, description, subject, material_type, course, unit_code, level)
SELECT t, 'Core unit in '||p||' as taught in Kenyan '||CASE l WHEN 'University' THEN 'universities' WHEN 'College' THEN 'colleges and TVET institutions' ELSE 'professional exams' END||'. Full notes read inside Franky''s.', s, 'Unit', p, a||' '||lpad((100*((n-1)/5+1)+n)::text,3,'0'), l FROM (
SELECT 'Bachelor of Science in Computer Science' p,'Computer Science' s,'University' l,'CS' a,x.t,x.n FROM unnest(ARRAY['Introduction to Computer Science','Programming Methodology (C)','Discrete Mathematics','Data Structures and Algorithms','Object Oriented Programming (Java)','Database Systems','Operating Systems','Computer Networks','Software Engineering','Computer Architecture','Theory of Computation','Artificial Intelligence','Web Application Development','Mobile Application Development','Information Security','Compiler Construction','Human Computer Interaction','Distributed Systems','Machine Learning','Computer Graphics']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Bachelor of Science in Information Technology','Information Technology','University','IT',x.t,x.n FROM unnest(ARRAY['Fundamentals of IT','Systems Analysis and Design','Network Administration','Cloud Computing','IT Project Management','E-Commerce','Management Information Systems','Cyber Security Fundamentals']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Bachelor of Commerce','Business','University','BCOM',x.t,x.n FROM unnest(ARRAY['Principles of Management','Financial Accounting I','Financial Accounting II','Microeconomics','Macroeconomics','Business Mathematics','Business Statistics','Principles of Marketing','Business Law','Cost Accounting','Management Accounting','Financial Management','Human Resource Management','Organisational Behaviour','Entrepreneurship and Innovation','Auditing and Assurance','Taxation','Strategic Management','Operations Management','Banking and Finance']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Bachelor of Education (Arts)','Education','University','EDU',x.t,x.n FROM unnest(ARRAY['Foundations of Education','Educational Psychology','Curriculum Development','Philosophy of Education','Sociology of Education','Educational Administration and Planning','Guidance and Counselling','Research Methods in Education','Instructional Methods','Measurement and Evaluation','Special Needs Education','History of Education in Kenya']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Bachelor of Education (Science)','Education','University','EDS',x.t,x.n FROM unnest(ARRAY['Teaching Methods in Mathematics','Teaching Methods in Biology','Teaching Methods in Chemistry','Teaching Methods in Physics','Educational Technology']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Bachelor of Laws (LLB)','Law','University','LAW',x.t,x.n FROM unnest(ARRAY['Legal Systems and Methods','Law of Contract','Law of Torts','Constitutional Law of Kenya','Criminal Law','Family Law and Succession','Land Law','Law of Evidence','Commercial Law','Administrative Law','Jurisprudence','Public International Law','Company Law','Civil Procedure','Human Rights Law','Labour Law']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Bachelor of Medicine and Bachelor of Surgery (MBChB)','Medicine','University','MED',x.t,x.n FROM unnest(ARRAY['Human Anatomy','Medical Physiology','Medical Biochemistry','Histology and Embryology','Medical Microbiology','Pathology','Pharmacology','Internal Medicine','General Surgery','Paediatrics and Child Health','Obstetrics and Gynaecology','Community Health and Epidemiology','Psychiatry']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Bachelor of Science in Nursing','Nursing','University','NUR',x.t,x.n FROM unnest(ARRAY['Fundamentals of Nursing','Anatomy and Physiology for Nurses','Medical-Surgical Nursing','Community Health Nursing','Maternal and Child Health Nursing','Mental Health Nursing','Nursing Pharmacology','Nursing Research','Nursing Leadership and Management']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Bachelor of Pharmacy','Pharmacy','University','PHA',x.t,x.n FROM unnest(ARRAY['Pharmaceutical Chemistry','Pharmaceutics','Pharmacognosy','Clinical Pharmacy','Pharmacy Law and Ethics']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Bachelor of Science in Civil Engineering','Engineering','University','ECE',x.t,x.n FROM unnest(ARRAY['Engineering Mathematics I','Engineering Mathematics II','Engineering Drawing','Strength of Materials','Fluid Mechanics','Surveying','Structural Analysis','Soil Mechanics','Reinforced Concrete Design','Highway Engineering','Hydraulics and Hydrology','Construction Management']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Bachelor of Science in Electrical and Electronic Engineering','Engineering','University','EEE',x.t,x.n FROM unnest(ARRAY['Circuit Theory','Analogue Electronics','Digital Electronics','Electromagnetic Fields','Signals and Systems','Electrical Machines','Power Systems','Control Systems','Telecommunications','Microprocessors and Microcontrollers']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Bachelor of Science in Mechanical Engineering','Engineering','University','EME',x.t,x.n FROM unnest(ARRAY['Engineering Mechanics (Statics and Dynamics)','Thermodynamics','Machine Design','Manufacturing Processes','Heat Transfer','Theory of Machines']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Bachelor of Science in Agriculture','Agriculture','University','AGR',x.t,x.n FROM unnest(ARRAY['Introduction to Agriculture','Crop Production','Soil Science','Animal Production','Agricultural Economics','Plant Pathology','Agricultural Extension','Farm Management','Agronomy','Horticulture']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Bachelor of Science (Mathematics)','Mathematics','University','MAT',x.t,x.n FROM unnest(ARRAY['Calculus I','Calculus II','Linear Algebra','Real Analysis','Complex Analysis','Ordinary Differential Equations','Probability and Statistics','Abstract Algebra','Numerical Methods','Operations Research']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Bachelor of Science (Physical and Biological Sciences)','Sciences','University','SCI',x.t,x.n FROM unnest(ARRAY['General Biology','Cell Biology','Genetics','Ecology','Botany','Zoology','General Chemistry','Organic Chemistry','Inorganic Chemistry','Physical Chemistry','Mechanics','Electricity and Magnetism','Modern Physics','Optics and Waves']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Bachelor of Arts','Humanities','University','ART',x.t,x.n FROM unnest(ARRAY['Introduction to Sociology','Introduction to Psychology','Political Science','International Relations','History of Kenya','African History','Geography of Kenya','Kiswahili: Isimu','Fasihi ya Kiswahili','English Literature','Linguistics','Philosophy','Criminology','Development Studies','Public Administration']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Bachelor of Journalism and Mass Communication','Communication','University','JMC',x.t,x.n FROM unnest(ARRAY['Introduction to Mass Communication','News Writing and Reporting','Media Law and Ethics','Broadcast Journalism','Public Relations','Digital Media']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Bachelor of Economics and Statistics','Economics','University','ECO',x.t,x.n FROM unnest(ARRAY['Econometrics','Development Economics','Public Finance','International Trade','Monetary Economics','Mathematical Statistics','Sampling Techniques']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Bachelor of Hospitality and Tourism Management','Hospitality','University','HTM',x.t,x.n FROM unnest(ARRAY['Introduction to Tourism','Food and Beverage Production','Front Office Operations','Housekeeping Management','Tour Guiding and Operations']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Common University Units','Common Units','University','CU',x.t,x.n FROM unnest(ARRAY['Communication Skills','Introduction to Critical and Creative Thinking','HIV/AIDS and Society','Development Studies','Information Literacy','Health Awareness and Life Skills','Environmental Studies']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'CPA (KASNEB)','Accounting','Professional','CPA',x.t,x.n FROM unnest(ARRAY['Financial Accounting','Introduction to Law and Governance','Economics','Quantitative Analysis','Public Finance and Taxation','Management Accounting','Financial Reporting','Auditing and Assurance','Advanced Financial Reporting','Advanced Management Accounting','Strategy, Governance and Ethics','Leadership and Management']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'CIFA / CS (KASNEB)','Accounting','Professional','KAS',x.t,x.n FROM unnest(ARRAY['Portfolio Management','Corporate Finance','Derivatives Analysis','Company Secretarial Practice','Corporate Governance']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Diploma in Information Communication Technology (KNEC/CDACC)','ICT (TVET)','College','DICT',x.t,x.n FROM unnest(ARRAY['Computer Applications','Introduction to Programming','Database Management','Web Design','Computer Maintenance and Repair','Networking Essentials','Structured Programming','Visual Programming','System Analysis and Design','Operating Systems Management']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Diploma in Business Management (KNEC)','Business (TVET)','College','DBM',x.t,x.n FROM unnest(ARRAY['Business Communication','Principles of Management','Office Administration','Business Calculations and Statistics','Purchasing and Supply','Sales and Marketing','Entrepreneurship Education','Human Resource Management','Commerce','Book-keeping and Accounts']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Diploma in Electrical Engineering (KNEC/CDACC)','Engineering (TVET)','College','DEE',x.t,x.n FROM unnest(ARRAY['Electrical Installation Technology','Electrical Principles','Electronics','Electrical Machines and Transformers','Workshop Technology','Technical Drawing','Power Transmission and Distribution']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Diploma in Mechanical and Automotive Engineering','Engineering (TVET)','College','DAE',x.t,x.n FROM unnest(ARRAY['Motor Vehicle Technology','Engine Systems','Vehicle Electrical Systems','Fitting and Machining','Welding and Fabrication']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Diploma in Building and Civil Engineering','Engineering (TVET)','College','DBC',x.t,x.n FROM unnest(ARRAY['Building Construction','Plumbing','Quantity Surveying','Land Surveying','Building Materials']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Diploma in Clinical Medicine (KMTC)','Health (TVET)','College','DCM',x.t,x.n FROM unnest(ARRAY['Clinical Methods','Anatomy for Clinical Officers','Physiology','Medicine','Surgery','Reproductive Health']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Diploma in Kenya Registered Community Health Nursing (KMTC)','Health (TVET)','College','KRCHN',x.t,x.n FROM unnest(ARRAY['Foundations of Nursing','Midwifery','Community Health','Nutrition and Dietetics','Health Records and Information']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Diploma in Early Childhood Development Education','Education (TVET)','College','ECDE',x.t,x.n FROM unnest(ARRAY['Child Development and Psychology','ECDE Curriculum','Play and Learning','Early Literacy and Numeracy','Health and Nutrition in ECDE']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Diploma in Primary Teacher Education (DPTE)','Education (TVET)','College','DPTE',x.t,x.n FROM unnest(ARRAY['Professional Studies','CBC Pedagogy','Teaching of English','Teaching of Kiswahili','Teaching of Mathematics','Teaching of Science and Technology']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Diploma in Food and Beverage / Catering','Hospitality (TVET)','College','DFB',x.t,x.n FROM unnest(ARRAY['Food Production','Food and Beverage Service','Food Safety and Hygiene','Nutrition','Pastry and Bakery']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Certificate/Diploma in Fashion Design and Hair Dressing','Creative (TVET)','College','DFD',x.t,x.n FROM unnest(ARRAY['Garment Construction','Fashion Illustration','Textile Science','Hairdressing and Beauty Therapy']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Diploma in Supply Chain Management (KISM)','Business (TVET)','College','DSCM',x.t,x.n FROM unnest(ARRAY['Principles of Procurement','Logistics and Transport','Stores Management','Public Procurement and Disposal Act']) WITH ORDINALITY x(t,n)
UNION ALL SELECT 'Diploma in Agriculture (TVET)','Agriculture (TVET)','College','DAG',x.t,x.n FROM unnest(ARRAY['Crop Husbandry','Livestock Production','Agricultural Engineering','Farm Records and Accounts','Agribusiness']) WITH ORDINALITY x(t,n)
) z;
CREATE TABLE public.chat_conversations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title text NOT NULL DEFAULT 'New chat',
  messages jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.chat_conversations TO authenticated;
GRANT ALL ON public.chat_conversations TO service_role;
ALTER TABLE public.chat_conversations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users manage own conversations" ON public.chat_conversations FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE INDEX chat_conversations_user_idx ON public.chat_conversations(user_id, updated_at DESC);
CREATE TRIGGER chat_conversations_updated_at BEFORE UPDATE ON public.chat_conversations FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();